### ISSUE TITLE
Hvordan vil vi støtte hhv. en pårørende / tiltalt

### ISSUE THREAD

**Issue by DKAiFan** [DKAiFan/Ord#15]

**Comment by Appel-101** [comment]
Vi har ingen støttefunktion. Der kunne ikke opnås konsensus ved fremlæggelse af forslaget.

**Comment by DKAiFan** [comment]
@Appel-101: Modtaget - Skal jeg helt fjerne den, eller kalde den noget andet?

**Comment by Appel-101** [comment]
Fjenes helt og laves om til menu punktet "Støt os". Hvilket er sket kan jeg se.
