### ISSUE TITLE
www - Definer mål, formål for hjemmesiden vs. facebook

### ISSUE THREAD

**Issue by DKAiFan** [DKAiFan/Ord#7]
Problem:
Det er uklart hvad hjemmesiden eksakt skal bruges til.

Der er pt. ønsker om:
1. Oplæg af nye artikler som "launch" (Marianne)
2. Opbevaring af medier såsom film, artikler, podcasts (Annegrethe)
3. Information omkring foreningen (alle?)
4. Hvervning af nye medlemmer (Jan) 

Bindinger:
a. Vi har også fået oprettet en FB side, som kan håndtere video, podcast mm mere smidigt end www kan. 

Sekundære problemer:
a. Det er problematisk at indsætte podcats, videoer, artikler fra en stor del af sider, da disse er gemt bag abbonoments ordninger. (RSS feed utilgængeligt)

**Comment by DKAiFan** [comment]
Forslag til formål:
At ændre den offentlige opinion om samtykkeloven ved at kombinere fakta, data og følelser på en måde, der engagerer og informerer brugerne.

Vi ønsker at skabe en platform, hvor vi kan formidle vores synspunkter og holdninger om lovens udfordringer, og samtidig give brugerne en dybdegående forståelse af årsagen. Vi tror på, at ved at kombinere fakta og data med følelser og personlige historier, kan vi ændre brugernes holdninger og motivere dem til at handle.

På vores FB side vil vi have en åben dialog med vores brugere, hvor vi lytter og engagerer dem. Vi ønsker at skabe platforme, hvor brugernes stemmer bliver hørt og værdsat.

**Comment by Appel-101** [comment]
Tanker til mål og formål med vores webside.

Mål med siden deles op delmål 1-2-3. Delmål 2-3 falder for nu i baggrunden. De gennemtænkes og der arbejdes på dem i baggrunden. De Implementeres enkelt vis over tid, når det giver mening. 

Delmål 1. Skal være færdigt og klart til at gå i luften inden for kort tid efter vi har registeret foreningen og har fået Bankkonto og Mobilpay. Efter testning af websidens offenliggøres den. Samtidig offenliggøres vores Pressemeddelelse.

Delmål 1.

Fuktionel overskuelig forsiden, med menu punkterne;
"Foreningen" "Samtykkeloven" "Kontakt" "Støt os" "Bliv medlem" "Retsikkerhed"

Websidens forsiden er altid dedikeret til Mariannes senest udgivet artikle. 

Menupunketet "Foreningen" Her indesættes vores formålserklæring som ligger klar og er lige til at sætte ind.

Menupunketet "Kontakt" Foreningens Mail adresse. med kort tekst om at man kan kontakte os med spørgsmål til foreningen og booking af foredrag med Marianne.

Menupunketet "Støt os" Mobilpay nr. og bank konto nr. til indbetaling af støtte beløb.

Menupunketet "Bliv medlem" Proceduren for indmeldelse i foreningen. Navn Adresse telefon osv. Se link i min Kommentar til "Proces for tilmelding af nye medlemer"

Menupunketet "Retsikkerhed" Her indsættes vores advokat liste. Der skrives en kort rådgivning, om hvordan man sikker sin retsikkerhed bedst, hvis man pludselig bliver anholdt, afhørt og sigtes generelt.

**Comment by DKAiFan** [comment]
@Appel-101 : Jeg har opdateret med nye overskrifter og har delt støtte op i to.
Hhv. økonomisk og praktisk støtte.

Du vil elske pkt 6 :)
