### ISSUE TITLE
Indsaml content til hjemmesiden.

### ISSUE THREAD

**Issue by DKAiFan** [DKAiFan/Ord#9]

**Comment by Appel-101** [comment]
Forslag til tekst under menu punktet "Retssikkerhed" ;

Skriv aldrig under på politiets afhøringsrapporter af dig, alt hvad du siger (underskriver), kan og vil blive brugt imod dig.

Lovlydige drenge og mænd har som regl aldrig haft med politiet at gøre. Derfor kommer det som et chock at politiet pludselig, enten afhenter dig i dit hjem, på jobbet eller indkalder dig til afhøring og sigter dig i en § 216 kontaktsamtykkesag.
Forvent ikke at der bliver taget hensyn til din sindstilstand ved afhøringen. Dette er kun anmelderen forundt, endda i absurdt rigelige mængder. Forvent ikke objektive afhøringer og efterforskning i sagen mod dig.

Det er vigtigt at man selv sikre sig beviser, så vidt det er muligt, ud fra den situation man er sat i af politiet.

I dagens Danmark har en betændt ekstrem feministisk dagorden fået fodfæste. Denne betændelse flyder nu også inden for politiet, anklagemyndigheden og domstolene. Resultatet af dette er at drenge og mænds retssikkerhed i kontaktsamtykkesager har fået koldbrand. Den satte satte ind, da samtykkeloven blev indført 1. januar 2021. Dette betyder at der nu reelt er omvendt bevisbyrde i kontaktsamtykkesager og at en uhæmmet heksejagt er sat igang, som lægger drenge og mænd liv i ruiner og sender dem i fængsel i årvis. Disse fængselsdomme uddeles som bolsjer, hvor grundlaget for dommene begrundes med troværdighed, som i virkeligheden dækker over sympati / mavefornemmelser. Ingen ojektive beviser er nødvendige idag for at dømme i disse ord mod ord sager.

Lad dig derfor aldrig afhøre af politiet, før du har talt med en forsvarsadvokat og kræv denne ved din side under afhøringen.
Brug aldrig en forsvarsadvokat politiet beskikker dig. Kræv at få tildelt en forsvarsadvokat med erfaring i § 216 kontaktsamtykkesager evt. en af dem listet her på siden.
